const tweets = [
  {
    img: 'http://placekitten.com.s3.amazonaws.com/homepage-samples/408/287.jpg',
    text: 'Ceci est un tweet',
    username: 'Lucas Charvolin',
    userimg: 'https://cdn.intra.42.fr/users/medium_lcharvol.jpg',
    date: '2 July',
    categories: 'Divertissement',
  },
  {
    img: 'http://placekitten.com.s3.amazonaws.com/homepage-samples/200/286.jpg',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tortor augue, ',
    username: 'Lucas Charvolin',
    userimg: 'https://cdn.intra.42.fr/users/medium_lcharvol.jpg',
    date: '2 July',
    categories: 'Divertissement',
  },
  {
    img: 'http://placekitten.com.s3.amazonaws.com/homepage-samples/200/287.jpg',
    text: 'Ceci est un tweet',
    username: 'Lucas Charvolin',
    userimg: 'https://cdn.intra.42.fr/users/medium_lcharvol.jpg',
    date: '2 July',
    categories: 'Politique',
  },
  {
    img: 'http://placekitten.com.s3.amazonaws.com/homepage-samples/200/140.jpg',
    text: 'Ceci est un tweet',
    username: 'Lucas Charvolin',
    userimg: 'https://cdn.intra.42.fr/users/medium_lcharvol.jpg',
    date: '2 July',
    categories: 'Divertissement',
  },
  {
    img: 'http://placekitten.com.s3.amazonaws.com/homepage-samples/200/138.jpg',
    text: 'Ceci est un tweet',
    username: 'Lucas Charvolin',
    userimg: 'https://cdn.intra.42.fr/users/medium_lcharvol.jpg',
    date: '2 July',
    categories: 'Musique',
  },
  {
    img: 'http://placekitten.com.s3.amazonaws.com/homepage-samples/200/139.jpg',
    text: 'Ceci est un tweet',
    username: 'Lucas Charvolin',
    userimg: 'https://cdn.intra.42.fr/users/medium_lcharvol.jpg',
    date: '2 July',
    categories: 'Politique',
  },
  {
    img: 'http://placekitten.com.s3.amazonaws.com/homepage-samples/408/287.jpg',
    text: 'Ceci est un tweet',
    username: 'Lucas Charvolin',
    userimg: 'https://cdn.intra.42.fr/users/medium_lcharvol.jpg',
    date: '2 July',
    categories: 'Divertissement',
  },
  {
    img: 'http://placekitten.com.s3.amazonaws.com/homepage-samples/200/286.jpg',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tortor augue',
    username: 'Lucas Charvolin',
    userimg: 'https://cdn.intra.42.fr/users/medium_lcharvol.jpg',
    date: '2 July',
    categories: 'Divertissement',
  },
  {
    img: 'http://placekitten.com.s3.amazonaws.com/homepage-samples/200/287.jpg',
    text: 'Ceci est un tweet',
    username: 'Lucas Charvolin',
    userimg: 'https://cdn.intra.42.fr/users/medium_lcharvol.jpg',
    date: '2 July',
    categories: 'Musique',
  },
  {
    img: 'http://placekitten.com.s3.amazonaws.com/homepage-samples/200/140.jpg',
    text: 'Ceci est un tweet',
    username: 'Lucas Charvolin',
    userimg: 'https://cdn.intra.42.fr/users/medium_lcharvol.jpg',
    date: '2 July',
    categories: 'Divertissement',
  },
  {
    img: 'http://placekitten.com.s3.amazonaws.com/homepage-samples/200/138.jpg',
    text: 'Ceci est un tweet',
    username: 'Lucas Charvolin',
    userimg: 'https://cdn.intra.42.fr/users/medium_lcharvol.jpg',
    date: '2 July',
    categories: 'Politique',
  },
  {
    img: 'http://placekitten.com.s3.amazonaws.com/homepage-samples/200/139.jpg',
    text: 'Ceci est un tweet',
    username: 'Lucas Charvolin',
    userimg: 'https://cdn.intra.42.fr/users/medium_lcharvol.jpg',
    date: '2 July',
    categories: 'Politique',
  },
];

export default tweets;
